### ISSUE TITLE
Possible bug with `sort.Slice` in the Staking Contract

### ISSUE THREAD

**Issue by 0x3639** [zenon-network/go-zenon#41]
ISSUE: 
Fork at  Height: 6606104, Hash: 5328a743cc5cad623f7f727a7e757b58446923ec40166f54ab2890e53c949a1c

Bad state: The client closed with pending request "embedded.pillar.getAll".

BACKGROUND:
At block height 6606104 it appears we suffered a fork.  Nodes are unable to sync past this block height.  We believe the fork was caused by `sort.Slice`  in the staking embedded contract.   We think this is the same [issue](https://github.com/zenon-network/go-zenon/pull/26) we encountered with the AZ Embedded Contract: the sort function is not returning the same values to all nodes.     

Possible location of the bug.  https://github.com/zenon-network/go-zenon/blob/d92e3bec1db6f98ee6490dffbfd93ccd2f89a5a6/chain/nom/momentum_content.go#L47

Can we investigate all instances of [sort.Slice](https://github.com/search?q=repo%3Azenon-network%2Fgo-zenon%20sort.Slice&type=code) in the code and update them?

**Comment by georgezgeorgez** [comment]
Sigh, yes this was mentioned during the fork of AZ.
Hopefully, changing to stable sort matches the surviving chain.

If it doesn't then it's a lot messier.
At this point in time, I would lean towards hardforking/new genesis than introducing spaghetti exceptions throughout the codebase.

**Comment by georgezgeorgez** [comment]
I will look into setting up some additional testing infrastructure. With every change we make, we need to backtest it against the existing chain. Deploying live and syncing is too slow.

**Comment by 0x3639** [comment]
> Hopefully, changing to stable sort matches the surviving chain.

How can I test and know the answer to this?  Is it possible that `sort.SliceStable` will sync the chain as expected, but produce inaccurate blocks without knowing it?

**Comment by 0x3639** [comment]
We've tested the following patch, and we cannot sync past `6606104`.  I think @georgezgeorgez @sumamu or @MoonBaZZe need to take a look at this.  We have an CEX syncing a node now to list $ZNN, and I don't think we can launch until this issue is resolved. 

https://github.com/zenon-network/go-zenon/compare/master...0x3639:go-zenon:fix/sort

**Comment by vilkris4** [comment]
I don't think this issue is related to `sort.Slice` nor the staking contract.

The `sort.Slice` function should always return the same order in this case since account block headers are unique. I don't see a need to change it to `SliceStable`, considering it would have poorer performance.

Also, changing it to `SliceStable` won't affect regular nodes that are just validating momentums, since the `NewMomentumContent` function is only called by a pillar when it's producing a momentum.

The issue appears to be that since in momentum `6606105`, the included account blocks are referencing very old states with momentumAcknowledged, nodes are running out of resources when trying to validate the momentum.

It takes a long time to validate `6606105` - this can be seen when comparing the timestamps of `6606105` and `6606106`. The same goes for `6162514` and `6162515`, which seems to be why you got stuck there, @0x3639.

So I think that many nodes just don't have enough resources to process the momentum. I've been able to sync past `6606104` multiple times on a relatively capable machine. RAM usage is over 12GB and CPU usage is high while processing the momentum. Low-end cloud servers will most likely struggle with it.

**Comment by 0x3639** [comment]
Thank you for this feedback. So for now, maybe we should recommend 4vCPUs and 16G of ram. I increased the node to these specs and got past `6162514`

 I will close this issue in the next few days waiting for final comments.

**Comment by coinselor** [comment]
My 4GB RAM VPS went through that block without issues when you initially forked out and I checked all my nodes.

**Comment by georgezgeorgez** [comment]
@vilkris4 thank you for the analysis. I haven't had a chance to dig into it. You are correct that if the sorted values are unique then there is no benefit for additional cost.
